### ISSUE TITLE
Only works if your output of `useStyles` is `classes`

### ISSUE THREAD

**Issue by jacobchrismarsh** [jens-ox/eslint-plugin-material-ui-unused-classes#10]
If your styles are created like this, then you're good:
```ts
const classes = useStyles()
```

If you use any other variable name, however, the plugin declares every class as "unused"

```ts
const different_classes = useStyles()

// Every class is marked as unused
```

**Comment by jens-ox** [comment]
Hi @jacobchrismarsh! Sorry for the late response.

I just released v2, which should be able to work in this scenario. I don't really work with Material UI anymore, so I don't have a real codebase at hand to test this with (although this is covered by test cases). Feel free to test v2.

You can close this issue if you're not using this plugin anymore.

**Comment by jacobchrismarsh** [comment]
That's awesome! I'll try it out later this week!
