### ISSUE TITLE
Doesn't understand createStyles

### ISSUE THREAD

**Issue by danvk** [jens-ox/eslint-plugin-material-ui-unused-classes#12]
Wrapping my styles with [`createStyles`](https://mui.com/system/styles/api/#createstyles-styles-styles) seems to defeat this plugin.

Here's an adapted example from the unit tests showing dead class detection working as expected:

```ts
import {makeStyles} from '@material-ui/core/styles';
import React from 'react';

const useStyles = makeStyles(theme => ({
  testClass: {
    backgroundColor: 'red',
  },
  usedClass: {
    backgroundColor: 'hotpink',
  },
}));

export const Component = () => {
  const classes = useStyles();
  return <div className={classes.usedClass}>test</div>;
};
```

<img width="664" alt="image" src="https://user-images.githubusercontent.com/98301/219422067-7efc7442-8d6f-447f-a025-bfdea0fc31f5.png">

When I throw a `createStyles` in there, the class is no longer marked as dead:

```ts
import {createStyles, makeStyles} from '@material-ui/core/styles';
import React from 'react';

const useStyles = makeStyles(theme =>
  createStyles({
    testClass: {
      backgroundColor: 'red',
    },
    usedClass: {
      backgroundColor: 'hotpink',
    },
  }),
);

export const Component = () => {
  const classes = useStyles();
  return <div className={classes.usedClass}>test</div>;
};
```

<img width="700" alt="image" src="https://user-images.githubusercontent.com/98301/219422140-ca9d089f-7525-4e18-9003-fdae3a1f1011.png">

**Comment by jens-ox** [comment]
Hi @danvk! I just released 2.0.1 which adds support for `createStyles` (although I don't really know why `createStyles` exists 😅)

Lmk if it works as expected!

**Comment by danvk** [comment]
Thanks @jens-ox! I'm not working on the project that prompted this issue any more, but @ludazhao might be interested.

**Comment by jens-ox** [comment]
Alright, closing this for - feel free to reopen if some problem remains!
