### ISSUE TITLE
Mocha listed as dependency seemingly unnecessary and causes warnings

### ISSUE THREAD

**Issue by sjdemartini** [jens-ox/eslint-plugin-material-ui-unused-classes#2]
The package.json appears to unnecessarily list its dependencies as `dependencies` rather than `devDependencies` or `peerDependencies`.

When installing this npm package, I got the following warning, since it began installing mocha for me:
`warning eslint-plugin-mui-unused-classes > mocha > debug@4.2.0: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)`

Mocha should be in the `devDependencies` presumably, since it's only needed to test the package when developing, and isn't needed by those who install the package.

I imagine the `@typescript-eslint/parser` and `eslint` itself could presumably be in `peerDependencies`, but less certain about this. (For instance, eslint-plugin-jsx-a11y lists eslint as a peerDependency and devDependency (but not dependency): https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/20b48a4110fef62165148a43269d955d82882cbc/package.json#L74. Same with Airbnb's eslint-config-airbnb: https://github.com/airbnb/javascript/blob/63098cbb6c05376dbefc9a91351f5727540c1ce1/packages/eslint-config-airbnb/package.json#L78)

**Comment by jens-ox** [comment]
Yeah, that can be tidied up, will fix it now :relaxed: 

Concerning putting it as devDependency and peerDependency - I assume that is to ensure that the dependency gets installed as peerDependencies are not installed by default or something like that.

**Comment by jens-ox** [comment]
Fixed in 5a09cc66e08d0d51326effbec642be4c5e0d1722, feel free to check it out!

**Comment by sjdemartini** [comment]
Awesome, thank you @jens-ox! Appreciate the quick action on my PR and the dependencies update 😃  and for publishing the updated version
