### ISSUE TITLE
Detects all classes as not used, even when they are

### ISSUE THREAD

**Issue by benmneb** [jens-ox/eslint-plugin-material-ui-unused-classes#5]
project made with `create-react-app` using `"react-scripts": "4.0.3"`

heres the relevent package.json:

`
	"eslintConfig": {
		"extends": [
			"react-app",
			"react-app/jest"
		],
		"plugins": [
			"mui-unused-classes"
		],
		"rules": {
			"mui-unused-classes/unused-classes": 1
		}
	},
	"devDependencies": {
		"eslint-plugin-mui-unused-classes": "^1.0.3"
	}
`

shows errors:
<img width="611" alt="Screen Shot 2021-06-28 at 10 42 16 am" src="https://user-images.githubusercontent.com/62878664/123571799-86c6da80-d7ba-11eb-8f93-93817f847f71.png">
<img width="318" alt="Screen Shot 2021-06-28 at 10 45 52 am" src="https://user-images.githubusercontent.com/62878664/123572043-f9d05100-d7ba-11eb-8fee-e10d4b8d194b.png">

even though the classes/styles are used:
<img width="847" alt="Screen Shot 2021-06-28 at 10 43 25 am" src="https://user-images.githubusercontent.com/62878664/123571854-a3631280-d7ba-11eb-9cd7-551359ab957a.png">

🤔 what am i doing wrong?

**Comment by chapati23** [comment]
i'm seeing the same result, using `makeStyles()`, maybe that's the issue?

**Comment by bmurtagh01** [comment]
Were you able to solve the problem? I have the exact same issue.

**Comment by jens-ox** [comment]
v1 of this plugin expects you to instantiate your styles as

```js
const classes = useStyles()
```

v2 (which I just released) is more flexible, you should be able to name your hook and the classes instance however you like.
