### ISSUE TITLE
support peer dependency eslint 7 || 8

### ISSUE THREAD

**Issue by artivilla** [jens-ox/eslint-plugin-material-ui-unused-classes#8]
Trying to update some of my packages and this lib has been really useful. Can put in PR for this to support peers 7 || 8
```
"peerDependencies": {
    "eslint": "^6.0.0 || ^7.0.0 || ^8.0.0"
},
```
Any suggestions on how to test this plugin?

**Comment by TomFreudenberg** [comment]
As long as this wont be fixed, you may use this repo:

https://github.com/4commerce-technologies-AG/eslint-plugin-material-ui-unused-classes

```
npm install --save-dev https://github.com/4commerce-technologies-AG/eslint-plugin-material-ui-unused-classes
```

**Comment by jens-ox** [comment]
Hi all! I just tagged and released v2, `eslint` is now set to `*` as peer dependency.
